### ISSUE TITLE
Tooltips sometimes aren’t disposed and stack in the UI

### ISSUE THREAD

**Issue by baldurh** [baldurh/atom-status-bar-blame#12]
Sometimes the tooltips aren’t disposed properly and therefore begin to stack up.
Haven’t figured out why this happens yet.

![image 2017-06-06 at 3 37 15 e h](https://user-images.githubusercontent.com/1823617/26837885-142cc296-4ace-11e7-8d69-271cf3fcee58.png)

**Comment by MoritzKn** [comment]
I've been seeing this since `v1.1.0`. Did we messed that up with #9..?

**Comment by baldurh** [comment]
I’ve been seeing this since before that. But it feels it got worse with `v1.1.0`.
I’ve been running #11 locally and it seems to fix this. It reads both the blame data and all commit messages on editor init and does no asynchronous actions when switching lines. So there is less chance of this ever happening. I just still have to fix the tests.

Also, I really want to refactor this a bit so that there’s way less code in the view and create an editor handler so there’s a separate handler for each tab/file which just communicate with the view.
But perhaps it’s better to get out a fix for this first and then go into the refactoring.

**Comment by MoritzKn** [comment]
> It reads both the blame data and all commit messages on editor init and does no asynchronous actions when switching lines.

I know about a performance issue in the "blame" package (josa42/atom-blame#31). This sounds like it could course this issue to emerge here too.

**Comment by MoritzKn** [comment]
I checked out the "optimizations" branch to fix the tooltip issue and works it for me too. Also my performance concerns were not confirmed.

**Comment by baldurh** [comment]
I’ve added a few more changes to #11. Gonna run it locally for a while and see how it behaves 😄

**Comment by baldurh** [comment]
Hopefully fixed by #15
