### ISSUE TITLE
Editor freezes after opening large files with log history

### ISSUE THREAD

**Issue by MoritzKn** [baldurh/atom-status-bar-blame#16]
After opening (grammar loads & syntax highlighting is shown) the editor freezes. This means scrolling and interacting with the editor is impossible. This state holds on for a few seconds.

This issue reminds me a whole lot of josa42/atom-blame#31.

**Comment by baldurh** [comment]
Thanks, will look into it 🙂

**Comment by baldurh** [comment]
Fixed by cf5874a2cf5d2a2d9d51d6d176b579b5934b6e6e 👍🏼
Version 2.0.1 has been released 🎉
Thanks for reporting 😊
