### ISSUE TITLE
unable to open http://gitlab....

### ISSUE THREAD

**Issue by btito** [baldurh/atom-status-bar-blame#3]
Hi, 

when using a non https (internal) gitlab server @ work the blame link to gitlab is forced to https..
Please consider a way to make it to fallback to http.

Thanks, Bob

**Comment by baldurh** [comment]
Thanks! I’ll look into it! :D

**Comment by baldurh** [comment]
Could you please tell me what the git remote url is for your repo? Or at least the format of the url?
For example:
`git config --get remote.origin.url`

I want to know what is not being covered.

**Comment by btito** [comment]
i'll do this first thing tomorrow.

Thanks, Bob

**Comment by btito** [comment]
Hi,

git config --get remote.origin.url
git@gitlab.hidden.dom:eid/broncode.git

When You click the link in the status bar the url to gitlab starts with https://gitlab.hidden.dom:eid <https://gitlab.hidden.dom:eid>

This works on gitlab instances on https, but the http ones cannot be reached.

Met vriendelijke groet / With kind regards, 
Bob Tito

**Comment by baldurh** [comment]
Fixed in 1.0.2
Now the fallback protocol is http instead of https. Better let the servers handle the https redirect themselves 😄 
Thanks Bob!

**Comment by btito** [comment]
Thanks!

working great now!


Met vriendelijke groet / With kind regards, 
Bob Tito

> Op 6 apr. 2017, om 08:14 heeft Bob Tito <bob@btito.net> het volgende geschreven:
> 
> Hi,
> 
> git config --get remote.origin.url
> git@gitlab.hidden.dom <mailto:git@gitlab.hidden.dom>:eid/broncode.git
> 
> When You click the link in the status bar the url to gitlab starts with https://gitlab.hidden.dom:eid <https://gitlab.hidden.dom:eid>
> 
> This works on gitlab instances on https, but the http ones cannot be reached.
> 
> Met vriendelijke groet / With kind regards, 
> Bob Tito
>
