### ISSUE TITLE
Status-bar tile persists after focusing non-editor pane

### ISSUE THREAD

**Issue by MoritzKn** [baldurh/atom-status-bar-blame#5]
If one for example opens the setting view or closes all editor tabs the status-bar tile with the blame info of the last focused line does not disappears.

I think therefore it has to listen to the [pane.onDidChangeActive](https://atom.io/docs/api/v1.17.0/Pane#instance-onDidChangeActive) event.

**Comment by baldurh** [comment]
Thanks! I‘ll take a look 😃

**Comment by baldurh** [comment]
Fixed by 18085830f42377bf4e8cafc384b927ea989bf2bd
Released as v1.0.5
Thanks again 👍

**Comment by MoritzKn** [comment]
Awesome, thank *you* for the quick fix.
