### ISSUE TITLE
Copy commit hash if no url is known

### ISSUE THREAD

**Issue by MoritzKn** [baldurh/atom-status-bar-blame#7]
When clicking on the status bar entry in a custom git repo (not GitHub or alike) it shows a notification: `Unknown url.`. It would be great if it would copy the commit hash instead. This way I could easily inspect the commit via the git-cli.

PS: very useful package, thx you for making it!

**Comment by baldurh** [comment]
Hmm there was an earlier issue which sounds similar (#3). This should be able to handle all kinds of repos.
Could you post the result of `git config --get remote.origin.url` ?

I’m not keen on changing any default behavior. But we could perhaps copy the hash if you hold down command/ctrl or something while clicking the status bar entry?

**Comment by MoritzKn** [comment]
> This should be able to handle all kinds of repos.

I don't think this is possible. A git remote address can take all kind of forms. It can even be just a path. In my case the git remote points to an internal domain and has the form `ssh://git@git.intern.foo.com/projects/myrepo.git`.

> But we could perhaps copy the hash if you hold down command/ctrl or something while clicking the status bar entry?

I think this would be an even better approach since it would allow to copy the hash for all kind of repos.

**Comment by baldurh** [comment]
OK I’ll see if I can work on it soon. I’m also happy to accept PRs 😉

**Comment by MoritzKn** [comment]
> I’m also happy to accept PRs

This evening I may have some time to implement this.

**Comment by MoritzKn** [comment]
Done, see #9 😄

**Comment by baldurh** [comment]
Released! Did some minor tweaks. Thanks again 😃

**Comment by MoritzKn** [comment]
Awesome. I like your tweaks :+1:
